all:
  children:
    vpn_servers:
      hosts:
        vpn-01:
          ansible_host: 192.0.2.10
        vpn-02:
          ansible_host: 192.0.2.11
        vpn-03:
          ansible_host: 192.0.2.12
      vars:
        ansible_user: root
